/**
 * Put the WebAssembly parser inside the package, as text.
 *
 * web-ifc ships `web-ifc.wasm` as a separate file and fetches it beside the
 * script that loaded it. That works when a host copies the file into its own
 * output, which means the host has to be told to do so: a postinstall step, a
 * bundler rule, or a served path. Every one of those is configuration a
 * consumer has to get right, and DTaaS has to work with no external network at
 * all.
 *
 * So the binary is written into a module as base64 and turned back into a blob
 * at runtime. It costs about a third more bytes than the file, in a chunk that
 * a host fetches only when someone actually converts a model, and it buys a
 * consumer that installs the package and nothing else.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const wasm = readFileSync(fileURLToPath(new URL('../node_modules/web-ifc/web-ifc.wasm', import.meta.url)));
const base64 = wasm.toString('base64');

mkdirSync('src/generated', { recursive: true });
writeFileSync('src/generated/wasm.ts', `/* eslint-disable */
// Generated by scripts/inline-wasm.mjs. Do not edit.
//
// web-ifc.wasm, ${(wasm.length / 1024).toFixed(0)} KB, as base64.

export const WEB_IFC_WASM_BASE64 =
  '${base64}';
`);

console.log(`  web-ifc.wasm inlined: ${(wasm.length / 1024).toFixed(0)} KB binary, ${(base64.length / 1024).toFixed(0)} KB base64`);
