"""Name the buildings in a models directory, from the IFC files themselves.

Writes `catalogue.json`, which bim-kit reads to show each model by the name
of the building it holds instead of by its file name. A file name says what
the file is called. It does not say what the building is.

Where the name comes from
-------------------------
An IFC file carries names on its project, its site and its building. Across
the models this was written against, the real name lives on the project's
LongName and not on the building:

    Building_1911_AK_v2         IfcProject.LongName  Pædagogisk Center
                                IfcBuilding.Name     Pædagosik Center (sic)
    2116_FEAS_kedelhuset        IfcProject.LongName  FEAS - Kommunehospital
                                IfcBuilding.Name     empty

So the project's LongName is read first, then its Name, then the building's.

Most models carry no name at all. A Revit export that nobody filled in keeps
the template text, "Project Name" and "Building Name", and the project's
Name is often a job number such as 34372. Neither is a building name, so both
are skipped, and a model with nothing else has no entry. bim-kit then shows
its file name, which is at least true.

Two files, two kinds of name
----------------------------
    catalogue.json             generated by this, from the IFC files. Nobody
                               edits it, because the next run replaces it.

    catalogue.overrides.json   optional, written by a person, for a building
                               whose file does not name it or names it wrong.
                               Applied on top, so an override always wins and
                               survives every regeneration.

Run it:

    ifc-to-catalogue common/models
    ifc-to-catalogue common/models --dry-run
"""

from __future__ import annotations

import argparse
import json
import logging
import re
import sys
from pathlib import Path

import ifcopenshell

LOG = logging.getLogger(__name__)

CATALOGUE_FILE = 'catalogue.json'
OVERRIDES_FILE = 'catalogue.overrides.json'

# Text an authoring tool writes into a new file and that nobody replaced.
# Compared case-insensitively.
PLACEHOLDERS = frozenset({
    'project name',
    'project number',
    'project status',
    'building name',
    'default',
    'site',
})

# A value made only of digits and separators is a job or project number, not a
# name: 0001, 34372, 39043-02.
IDENTIFIER = re.compile(r'^[\d\s./_-]+$')


def usable(value: object) -> str | None:
    """The value as a name, or None when it is empty, a placeholder or a number."""
    if not isinstance(value, str):
        return None
    text = value.strip()
    if not text or text.lower() in PLACEHOLDERS or IDENTIFIER.match(text):
        return None
    return text


def building_name(model: ifcopenshell.file) -> str | None:
    """The name of the building a model holds, or None when it does not say."""
    candidates = []
    for project in model.by_type('IfcProject'):
        candidates += [getattr(project, 'LongName', None), project.Name]
    for building in model.by_type('IfcBuilding'):
        candidates += [getattr(building, 'LongName', None), building.Name]

    for candidate in candidates:
        name = usable(candidate)
        if name:
            return name
    return None


def read_json(path: Path) -> dict[str, str]:
    """A name map from a file, or an empty one when the file is absent.

    Only string values are kept, so a mistake in a hand-written overrides file
    drops one entry instead of the whole file.
    """
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding='utf-8'))
    if not isinstance(data, dict):
        raise ValueError(f'{path} must hold an object mapping file names to titles')
    return {
        str(key): value.strip()
        for key, value in data.items()
        if isinstance(value, str) and value.strip()
    }


def build_catalogue(
    names: dict[str, str | None],
    overrides: dict[str, str],
) -> dict[str, str]:
    """Titles by file name: what the files say, then what a person said.

    A name two files share identifies neither of them, so it is dropped for
    both and each keeps its file name. The two substation models are the case:
    both are named "SWiM district cooling substation", and their file names are
    the only thing that tells them apart.
    """
    counts: dict[str, int] = {}
    for name in names.values():
        if name:
            counts[name] = counts.get(name, 0) + 1

    catalogue = {
        file: name
        for file, name in names.items()
        if name and counts[name] == 1
    }
    catalogue.update(overrides)
    return dict(sorted(catalogue.items()))


def scan(directory: Path) -> dict[str, str | None]:
    """The building name of every IFC file in a directory, keyed by file name."""
    names: dict[str, str | None] = {}
    for path in sorted(directory.glob('*.ifc')):
        try:
            names[path.name] = building_name(ifcopenshell.open(str(path)))
        except Exception as error:  # noqa: BLE001  one bad file must not stop the rest
            LOG.warning('%s could not be read: %s', path.name, error)
            names[path.name] = None
    return names


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description='Name the buildings in a models directory, from the IFC files.',
    )
    parser.add_argument('directory', type=Path, help='the directory holding the IFC files')
    parser.add_argument(
        '--dry-run',
        action='store_true',
        help='print the catalogue instead of writing it',
    )
    args = parser.parse_args(argv)
    logging.basicConfig(level=logging.INFO, format='%(message)s')

    if not args.directory.is_dir():
        parser.error(f'{args.directory} is not a directory')

    names = scan(args.directory)
    overrides = read_json(args.directory / OVERRIDES_FILE)
    catalogue = build_catalogue(names, overrides)

    for file, name in names.items():
        if file in overrides:
            LOG.info('%-45s %s (override)', file, overrides[file])
        elif file in catalogue:
            LOG.info('%-45s %s', file, catalogue[file])
        elif name:
            # Said, because the file does name a building: the name is simply
            # not enough to tell this file from another one.
            LOG.info('%-45s %s, shared with another file', file, name)
        else:
            LOG.info('%-45s no name in the file', file)

    text = json.dumps(catalogue, indent=2, ensure_ascii=False) + '\n'
    if args.dry_run:
        sys.stdout.write(text)
        return 0

    target = args.directory / CATALOGUE_FILE
    target.write_text(text, encoding='utf-8')
    LOG.info('wrote %d of %d titles to %s', len(catalogue), len(names), target)
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
