/**
 * Binding live sensor readings to the objects of a BIM model.
 *
 * What this package is for
 * ------------------------
 * A building model says where things are. A sensor stream says what they
 * measure. Nothing in either says which reading belongs to which wall. The
 * manifest does, by IFC GlobalId, and this package is the code that reads it.
 *
 * It is the piece DTaaS issue 1762 calls load-bearing: if the manifest schema
 * is right, the conversion, the viewer and the transport can each be replaced
 * without touching the others.
 *
 * What it does not do
 * -------------------
 * It draws nothing and imports no renderer, so it runs in jsdom, in Node and
 * in a browser alike. The DTaaS client's unit tests run in jsdom, where WebGL,
 * workers and WASM do not exist, and anything testable without a canvas is
 * kept where it can be tested.
 *
 * It also reads no IFC. Conversion runs outside the browser, in Python, and
 * produces the geometry and the manifest this consumes.
 *
 * The schema validator is a separate entry point, `@into-cps-association/bim-kit/schema`,
 * because it needs zod and most consumers do not: a manifest generated by the
 * converter has already been validated once.
 */

export {
  objectOf,
  topicOf,
  displayOf,
  idOf,
  type Binding,
  type Display,
  type Selector,
} from './binding.js';

export {
  resolveBindings,
  topicsOf,
  bindingsByTopic,
  type Resolved,
  type Unresolved,
  type ResolveResult,
  type SceneObject,
} from './resolver.js';

export { rampColour, RAMP_STOPS } from './ramp.js';

export {
  alertsOf,
  alertCounts,
  MEASURED_KIND,
  type Alert,
  type AlertLevel,
} from './alerts.js';

export {
  bandsFrom,
  bandOf,
  MERGE_WITHIN_M,
  FLOOR_MARGIN_M,
  type Band,
  type ObjectBase,
} from './storeys.js';

export {
  ageOf,
  ageText,
  isLive,
  zoneOf,
  zonesOf,
  availableScopes,
  ALL_SCOPES,
  DEFAULT_STALE_AFTER_S,
  type FeedState,
  type HeatScope,
  type Reading,
  type Zones,
} from './readings.js';
